version: "3.8"

services:
  octoapp-elegoo:
    image: ubuntu:22.04
    container_name: octoapp-elegoo
    restart: unless-stopped
    tty: true
    environment:
      - USERNAME=root
      - USER=root
      - HOME=/root
    volumes:
      - octoapp_data:/root/octoapp
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y git curl sudo bash coreutils python3 python3-pip &&
      cd /root &&
      if [ -d octoapp/.git ]; then
        echo 'Repo déjà présent → mise à jour' &&
        cd octoapp && git pull;
      else
        echo 'Repo absent → clonage' &&
        rm -rf octoapp &&
        git clone https://github.com/crysxd/OctoApp-Plugin octoapp;
      fi &&
      cd octoapp &&
      chmod +x install.sh &&
      yes '' | ./install.sh -elegoo &&
      echo 'Installation automatique terminée ✅' &&
      tail -f /dev/null
      "

volumes:
  octoapp_data:
