version: "3.8"

services:
  octoapp-elegoo:
    image: ubuntu:22.04
    container_name: octoapp-elegoo
    restart: unless-stopped
    tty: true
    volumes:
      - octoapp_data:/root/octoapp
  

volumes:
  octoapp_data:
