version: "3.8"

services:
  octoapp-elegoo:
    image: alpine:latest
    container_name: octoapp-elegoo
    tty: true
    restart: unless-stopped
    volumes:
      - octoapp_data:/data
    command: >
      /bin/sh -c "
      apk update &&
      apk add --no-cache git bash python3 py3-pip &&
      cd /home || cd / &&
      git clone https://github.com/crysxd/OctoApp-Plugin octoapp &&
      cd octoapp && git checkout release &&
      chmod +x install.sh &&
      ./install.sh -elegoo &&
      echo 'OctoApp Elegoo Connect installé avec succès.' &&
      tail -f /dev/null
      "
    networks:
      - octoapp-net

volumes:
  octoapp_data:

networks:
  octoapp-net:
