version: "3.8"

services:
  octoapp-elegoo:
    image: ubuntu:22.04
    container_name: octoapp-elegoo
    restart: unless-stopped
    tty: true
    environment:
      - USERNAME=root
      - USER=root
      - HOME=/root
      - PRINTER_IP=192.168.7.38   # 🔑 Mets ici l'IP de ta Centauri
    network_mode: host   # nécessaire pour que le conteneur voie ton imprimante
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y git curl sudo bash coreutils python3 python3-pip &&
      rm -rf /root/octoapp &&
      git clone https://github.com/crysxd/OctoApp-Plugin /root/octoapp &&
      cd /root/octoapp &&
      chmod +x install.sh &&
      yes '' | ./install.sh -elegoo <<EOF
      $PRINTER_IP
      EOF
      &&
      echo 'Installation automatique terminée ✅ avec IP $PRINTER_IP' &&
      tail -f /dev/null
      "
