version: "3.8"

services:
  octoapp-elegoo:
    image: ubuntu:22.04
    container_name: octoapp-elegoo
    restart: unless-stopped
    tty: true
    volumes:
      - octoapp_data:/root/octoapp
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y git curl sudo bash &&
      cd /root &&
      git clone https://github.com/crysxd/OctoApp-Plugin octoapp &&
      cd octoapp &&
      chmod +x install.sh &&
      ./install.sh -elegoo &&
      echo 'Installation terminée – suivez les invites à l’écran' &&
      tail -f /dev/null
      "

volumes:
  octoapp_data:
