---
- name: Redéployer un stack Portainer par nom
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Authentification à l'API Portainer
      uri:
        url: "https://192.168.7.251:9443/api/auth"
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
        body:
          username: "admin"
          password: "swm#rWRbH47d$e"
        return_content: yes
        validate_certs: no
      register: portainer_auth

    - name: Extraire le token JWT
      set_fact:
        portainer_token: "{{ portainer_auth.json.jwt }}"

    - name: Obtenir la liste des stacks
      uri:
        url: "https://192.168.7.251:9443/api/stacks"
        method: GET
        headers:
          Authorization: "Bearer {{ portainer_token }}"
        return_content: yes
        validate_certs: no
      register: stack_list

    - name: Trouver le stack par nom
      set_fact:
        matched_stack: "{{ item }}"
      loop: "{{ stack_list.json }}"
      when: item.Name == "elegoconnect"

    - name: Échec si aucun stack ne correspond
      fail:
        msg: "Stack 'elegoconnect' non trouvé."
      when: matched_stack is not defined

    - name: Redéployer le stack
      uri:
        url: "https://192.168.7.251:9443/api/stacks/{{ matched_stack.Id }}/restart"
        method: POST
        validate_certs: no
        headers:
          Authorization: "Bearer {{ portainer_token }}"
        status_code: 200

    - name: Succès
      debug:
        msg: "Le stack 'elegoconnect' a été redéployé avec succès."
