---
- name: Redéployer un stack dans Portainer
  hosts: localhost
  gather_facts: no
 
  vars:
    portainer_host: "https://192.168.7.251:9443"
    portainer_api_url: "{{ portainer_host }}/api"
    portainer_user: "admin"
    portainer_password: "swm#rWRbH47d$e"
    portainer_stack_name: "elegooconnectgit"

    
  tasks:
    - name: Authentifier avec l'API de Portainer
      uri:
        url: "{{ portainer_api_url }}/auth"
        method: POST
        body_format: json
        headers:
          Content-Type: application/json
        body:
          Username: "{{ portainer_user }}"
          Password: "{{ portainer_password }}"
        validate_certs: no
        return_content: yes
      register: login_response

    - name: Extraire le token JWT
      set_fact:
        jwt_token: "{{ login_response.json.jwt }}"

    - name: Obtenir la liste des stacks
      uri:
        url: "{{ portainer_api_url }}/stacks"
        method: GET
        headers:
          Authorization: "Bearer {{ jwt_token }}"
        validate_certs: no
        return_content: yes
      register: stacks_response

    - name: Trouver l'ID du stack cible
      set_fact:
        target_stack_id: "{{ item.Id }}"
      loop: "{{ stacks_response.json }}"
      when: item.Name == portainer_stack_name

    - name: Redéployer le stack
      uri:
        url: "{{ portainer_api_url }}/stacks/{{ target_stack_id }}/redeploy"
        method: POST
        headers:
          Authorization: "Bearer {{ jwt_token }}"
        validate_certs: no
        status_code: 200
