---
- name: Redémarrer le serveur
  hosts: all  # Remplacez par le groupe ou l'hôte cible
  remote_user: ansible
  become: true  # Utilise sudo
  tasks:
    - name: Redémarrer la machine
      reboot:
      register: reboot_result

    - name: Attendre que le serveur redémarre
      wait_for:
        port: 22  # Vérifie le port SSH
        delay: 10  # Délai avant de commencer à vérifier
        timeout: 300  # Temps d'attente total
        state: started  # Attendez que le service soit accessible
      when: reboot_result is changed

