---
- name: Redémarrer le serveur Ubuntu
  hosts: all  # Remplacez par le groupe ou l'hôte cible
  remote_user: ansible
  become: true  # Utilise sudo pour les privilèges d'administration
  tasks:
    - name: Redémarrer le serveur
      ansible.builtin.command:
        cmd: reboot
      async: 1  # Exécute la commande de redémarrage de manière asynchrone
      poll: 0  # Ne pas attendre la fin de la tâche
      ignore_errors: true  # Ignore les erreurs de connexion après le redémarrage

    - name: Attendre que le serveur redémarre
      ansible.builtin.wait_for:
        timeout: 300  # Temps d'attente maximal en secondes
        state: started
        host: "{{ inventory_hostname }}"  # Attendre que le serveur soit de nouveau accessible
      when: ansible_distribution == 'Ubuntu'  # Optionnel : attendre seulement pour Ubuntu
