---
- name: Mettre à jour et redémarrer le serveur si nécessaire
  hosts: all  # Remplacez par le groupe ou l'hôte cible
  remote_user: ansible
  become: true  # Utilise sudo
  tasks:
    - name: Mettre à jour le cache des paquets
      ansible.builtin.apt:
        update_cache: yes

    - name: Mettre à jour les paquets
      ansible.builtin.apt:
        upgrade: dist  # ou utilisez 'upgrade: yes' pour mettre à jour tous les paquets
    
    - name: Vérifier si un redémarrage est nécessaire sur Ubuntu
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Redémarrer la machine si nécessaire
      reboot:
      when: reboot_required.stat.exists
      register: reboot_result

    - name: Attendre que le système redémarre
      wait_for:
        timeout: 300
      when: reboot_result is changed

